name: example
description: A example of pedantic_mono.
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  meta: any

dev_dependencies:
  pedantic_mono:
    path: ..
